<form action="<?= route('posts.update', ['id' => $post->id]) ?>" method="POST" class="<?= $post->hasErrors() ? '' : 'was-validated' ?>" novalidate>
  <input type="hidden" name="_method" value="PUT">

  <div class="mb-3">
    <label for="post_title" class="form-label">Título:</label>
    <input type="text" name="post[title]" class="form-control" id="post_title" value="<?= $post->title ?>" required>
    <div class="invalid-feedback"><?= $post->errors('title') ?: '' ?></div>
  </div>

  <div class="mb-3">
    <label for="post_content" class="form-label">Conteúdo:</label>
    <textarea name="post[body]" class="form-control" id="post_content" required><?= $post->body ?></textarea>
    <div class="invalid-feedback"><?= $post->errors('body') ?: '' ?></div>
  </div>

  <div class="mb-3">
    <label for="post_published_at" class="form-label">Data de Publicação:</label>
    <input type="datetime-local" name="post[date]" class="form-control" id="post_published_at" value="<?= $post->date ?>" required>
    <div class="invalid-feedback"><?= $post->errors('date') ?: '' ?></div>
  </div>

  <div class="mb-3">
    <label for="tags" class="form-label">Tags:</label>
    <select name="tags[]" id="tags" class="form-select" multiple required>
      <?php foreach ($tags as $tag): ?>
        <option value="<?= $tag->id ?>">
          <?= htmlspecialchars($tag->name) ?>
        </option>
      <?php endforeach; ?>
    </select>
  </div>

  <button type="submit" class="btn btn-primary">Atualizar</button>
</form>

